### ISSUE TITLE
Cards with Max-height

### ISSUE THREAD

**Issue by antoninadert** [papercss/papercss#152]
Hello,

I would like to have a maximum height on the cards, so that I can control that a card is always fully visible in the viewport.

I didn't find a simple way to make it by adding the property on the card container, because the box will resize but the content will overflow by the bottom of the container.

so I ask the community if there is a simple way to do it by adding some CSS? 

Ideally the full content of the card would resize according to this height property: I would get smaller image, or smaller text, with respect to ratio of the existing card element

**Comment by rhyneav** [comment]
Hi! Could you please provide an image of what you mean by "the content will overflow by the bottom of the container"?

If I understand correctly, you may have to use media queries to change the text size in order to keep it in the box:
```css
@media all and (min-width: 50px)   {  body  { font-size:0.1em;  } }
@media all and (min-width: 100px)  {  body  { font-size:0.2em;  } }
@media all and (min-width: 200px)  {  body  { font-size:0.4em;  } }
@media all and (min-width: 300px)  {  body  { font-size:0.6em;  } }
@media all and (min-width: 400px)  {  body  { font-size:0.8em;  } }
@media all and (min-width: 500px)  {  body  { font-size:1.0em;  } }
@media all and (min-width: 600px)  {  body  { font-size:1.2em;  } }
@media all and (min-width: 700px)  {  body  { font-size:1.4em;  } }
@media all and (min-width: 800px)  {  body  { font-size:1.6em;  } }
@media all and (min-width: 900px)  {  body  { font-size:1.8em;  } }
@media all and (min-width: 1000px) {  body  { font-size:2.0em;  } }
```

It might also be worth looking into using `overflow: scroll;` if you'll have many boxes of different length text. Otherwise, you might need to tap into JS.

Please let me know if I misunderstood!
