### ISSUE TITLE
Default background color for `<html>` element

### ISSUE THREAD

**Issue by tonghoangvu** [papercss/papercss#274]
I've started a new project using Paper CSS recently. But I got a problem,  the background color is white when dark mode is enabled.

![image](https://user-images.githubusercontent.com/64119341/162599782-80beb999-8a32-4da3-b79c-0071555d7b92.png)

I think it would be better if the `<html>` element has a default background color, something like this.

```css
html {
    background-color: var(--main-background);
}
```
