### ISSUE TITLE
Host font locally

### ISSUE THREAD

**Issue by John-H-Smith** [papercss/papercss#284]
As of some changes in the eu-gdpr, loading google fonts directly from google is not allowed anymore.
As the url of the google font 'neucha' is hardcoded within the css file, using papercss is not easy anymore for all website owners in the eu.
So, I would highly appreciate if there is an option of using papercss with the neucha font hosted locally.
Currently, I worked arount with manually changing to a local hosted font, but it's not future proof for updates and so on.

**Comment by rhyneav** [comment]
Hey @John-H-Smith, I think some update here makes sense. What does your current override look like? We currently conditionally import the Google font based on if it is set:

```scss
// _config.scss

// The src for fonts (false to disable)
$font-src: 'https://fonts.googleapis.com/css?family=Neucha|Patrick+Hand+SC&display=swap' !default;

// Imports
@if $font-src {
  @import url($font-src);
}

```

I wonder if making a switch over to something like [Font Source](https://fontsource.org/) and totally leaving the Google ecosystem would be a good step forward, but curious to hear what would work best for you and other EU website owners.
