### ISSUE TITLE
Popover triggered by transparent pseudo-element

### ISSUE THREAD

**Issue by donmccurdy** [papercss/papercss#297]
When hovering over the space occupied by the (transparent) popover pseudo-element, the popover itself is triggered to appear. This is visible in the official examples: https://www.getpapercss.com/docs/components/popovers/

Because there might be other content in that space, and it would be obscured by the popover, I think it'd be best to prevent this behavior. The fix could be something like...

```css
[popover-x]::after {
  visibility: hidden;
}
[popover-x]:hover::after {
  visibility: visible;
}
```

... with some additional handling for the opacity transition. Would it be OK for me to make a PR with these changes?
